Add ScheduleParser
yurii-litvinov/StateExamSecretary pull request #1
Opened 2024-05-20 02:34 UTC by mawekk

2024-05-25 16:44 UTC, yurii-litvinov requested changes
Юнит-тесты бы ещё.

2024-05-25 16:44 UTC, yurii-litvinov commented on .github/workflows/ci.yml
> +    runs-on: ubuntu-latest
Мы, наверное, хотим ещё на Windows проверять

2024-05-25 16:44 UTC, yurii-litvinov commented on ScheduleParser/Config/Config.cs
> +public class Config
Надо комментарии ко всем public-классам и public-членам классов

2024-05-25 16:44 UTC, yurii-litvinov commented on ScheduleParser/Config/Config.cs
> +namespace ScheduleParser.Config;
namespace обычно первой строкой в файле пишется, а using уже под (чтобы имена импортировались в контексте текущего пространства имён, а не в глобальное пространство имён)

2024-05-25 16:44 UTC, yurii-litvinov commented on ScheduleParser/Config/Config.cs
> +using System.Text.Json.Serialization;
В идеале каждому файлу надо шапку с информацией о лицензии, StyleCop будет рекомендовать и проверять, что она есть

2024-05-25 16:44 UTC, yurii-litvinov commented on ScheduleParser/Config/Config.cs
> +    [JsonPropertyName("Темы ВКР, бакалавры МОиАИС")]
Надо пустую строку между членами класса

2024-05-25 16:44 UTC, yurii-litvinov commented on ScheduleParser/Models/CommissionMeeting.cs
> +    public List<StudentWork> StudentWorks = studentWorks;
- public-полей быть не должно вообще, они в принципе не имеют права на существование :)
- Это всё сгенерит компилятор, если сделать CommissionMeeting record-ом, а не классом

2024-05-25 16:44 UTC, yurii-litvinov commented on ScheduleParser/Program.cs
> +var jsonString = File.ReadAllText("../../../test.json");
../../../ явно излишни, файл должен быть по идее в текущей рабочей папке. Если ведёте разработку под Visual Studio/Rider, там можно рабочую папку проекта указать в свойствах отладки

2024-05-25 16:44 UTC, yurii-litvinov commented on ScheduleParser/Program.cs
> +catch (Exception e)
Никогда не ловите Exception, тем более только для того, чтобы показать Message. Потому что стек вызовов смотреть, конечно же, никому не нужно? :)

2024-05-25 16:44 UTC, yurii-litvinov commented on ScheduleParser/Program.cs
> +    var parser = new ScheduleParser.ScheduleParser(config!);
Не используйте `!`. Если он может быть null, в коде должно быть явно написано, что делать, если он null. nullability-анализ не дураки с таким трудом в язык внедряли.

2024-05-25 16:44 UTC, yurii-litvinov commented on ScheduleParser/ScheduleParser.cs
> +        var meetingInfo = cells[0][2].StringCellValue;
Это капец как неустойчиво к смене формата таблицы. Вынесите хоть в константы. Я вон в F#-версии специально делал, чтобы можно было по именам столбцов получать.

2024-05-25 16:44 UTC, yurii-litvinov commented on ScheduleParser/ScheduleParser.cs
> +            "бакалавры МОиАИС" => config.BachelorsMs,
Бакалавров МОиАИС больше нет, есть техпрог

2024-05-25 16:44 UTC, yurii-litvinov commented on ScheduleParser/ScheduleParser.cs
> +    }
```suggestion
    private bool CellsAreEmpty(List<ICell> cells)
        => cells.All(cell => cell.CellType == CellType.Blank);
```
И ниже, для всех методов-однострочников. А ещё, если метод не использует состояние объекта, его надо сделать static-ом

2024-05-25 16:44 UTC, yurii-litvinov commented on ScheduleParser/ScheduleParser.csproj
> +        <PackageReference Include="NPOI" Version="2.7.0" />
Подключите ещё StyleCop.Analyzers

2024-05-25 16:44 UTC, yurii-litvinov commented on ScheduleParser/YandexDiskDownloader.cs
> +
Тут лишняя пустая строчка

2024-05-26 23:07 UTC, mawekk commented on ScheduleParser/Models/CommissionMeeting.cs
> +    public List<StudentWork> StudentWorks = studentWorks;
не совсем понимаю, почему здесь не может быть public-полей: в моем случае модели являются простыми наборами данных, в них отсутствует какая-либо логика, а обращение к их полям будет происходить далее в бизнес-логике

также из-за немутабельности record-ов повышается сложность кода, так как консультанты лежат в другой таблице и назначаются уже существующей работе студента

2024-05-27 12:14 UTC, yurii-litvinov commented on ScheduleParser/Models/CommissionMeeting.cs
> +    public List<StudentWork> StudentWorks = studentWorks;
Это правило объектно-ориентированного программирования такое — public-полей нет. В C# для этого есть свойства, в Java приходилось писать геттеры и сеттеры или пользоваться Lombok, которая умела их генерить. Немутабельность тоже не проблема — в функциональных языках вообще ничего мутабельного нет. Делают либо изменённую копию, либо два отдельных record-а — с консультантом и без, первый создают по второму. Второй подход предпочтительнее, поскольку не позволяет выразить некорректные данные.

2024-05-27 12:23 UTC, yurii-litvinov commented on .github/workflows/ci.yml
> +        run: dotnet format
Если билды под разные ОС ничем не отличаются, используйте [build matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs)

2024-05-27 12:23 UTC, yurii-litvinov commented on ScheduleParser/Config/Config.cs
> +    Justification = "Conflict with the Rider linter.")]
Rider не нужен, настройте Rider лучше

2024-05-27 12:23 UTC, yurii-litvinov commented on ScheduleParser/Models/CommissionMeeting.cs
> +public class CommissionMeeting(string timeAndAuditorium, string meetingInfo, List<StudentWork> studentWorks)
Так и для DTOшек комментарии бы нелишни. Что они такое по сути с точки зрения предметной области. Не "Класс для сериализации в JSON", а "Одно заседание ГЭК, которых может быть несколько в один день"

2024-05-27 12:23 UTC, yurii-litvinov commented on ScheduleParser/Program.cs
> +    new ScheduleParser.ScheduleParser(config ?? throw new NullReferenceException("Файл конфигурации имеет неверный формат"));
NullReferenceException никогда не бросайте, оно для .NET-машины и всегда обозначает разыменование null из-за ошибки в коде. Тут лучше какое-нибудь своё исключение.

2024-06-12 13:22 UTC, yurii-litvinov approved these changes
Оно в целом ок, но у меня с Яндекса не качает (давайте по умолчанию все данные должны будут браться из рабочей папки). Это замерджим (но надо будет README поправить, чтобы там была инструкция по сборке и запуску, и что куда класть), и дальше уже надо генерацию и загрузку.

2024-06-12 13:22 UTC, yurii-litvinov commented on ScheduleParserTest/ScheduleParserTest.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
Обычно проекты с тестами в .NET именуют как <имя исходного проекта>.Test, чтобы неймспейс "Test" синтаксически был внутри неймспейса основного проекта. Но это можно уже потом поправить.

2024-06-12 13:22 UTC, yurii-litvinov commented on ScheduleParser/Program.cs
> +var jsonString = File.ReadAllText(Path.Combine("Config", "example.json"));
Наверное, в боевом коде конфиг должен называться уже не example.json

2024-06-12 13:22 UTC, yurii-litvinov commented on ScheduleParser/ScheduleParser.csproj
> +
Если добавить 
```xml
    <ItemGroup>
      <Content Include="Config\example.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>
```
то конфиг будет класться куда нужно при сборке. То же можно проделать с "Расписание.xlsx"

2024-06-12 13:22 UTC, merged